apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    run: react-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: react-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 2
  template:
    metadata:
      labels:
        run: react-app
    spec:
      containers:
      - name: react-app
        image: harounaouissaoui/react-app:v1
        ports:
        - containerPort: 80
        - containerPort: 443